#!/bin/bash
set -euo pipefail

WORKFLOW_PATH="$SERVICE_PATH/workflows/aws/log.yaml"
OVERRIDES_WORKFLOW_PATH="$OVERRIDES_PATH/workflows/aws/log.yaml"

CMD=(np service workflow exec --no-output --workflow "$WORKFLOW_PATH")

if [[ -f "$OVERRIDES_WORKFLOW_PATH" ]]; then
  CMD+=(--overrides "$OVERRIDES_WORKFLOW_PATH")
fi

"${CMD[@]}"
