#!/bin/bash
set -euo pipefail

if [ "$NOTIFICATION_ACTION" = "metric:list" ]; then
  exec "$SERVICE_PATH/scripts/aws/list_metrics"
fi

export ASSUME_ROLE_QUIET=true
source "$SERVICE_PATH/utils/assume_role_step"

exec "$SERVICE_PATH/scripts/aws/fetch_metric"
