name: tests

on:
  pull_request:
    branches:
      - main

jobs:
  do-tofu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: bash tests/do_tofu_version.sh valkey/scripts/aws/do_tofu
